version: '3'
services:
    node_alice:
        image: lsaether/polkadot:fast-fixed
        ports:
            - "30335:30335"
            - "9945:9945"
        volumes:
            - "polkadot-data-alice:/alice"
        command: polkadot --chain=polkadot-local --telemetry-url ws://172.28.1.3:8000/submit --validator --unsafe-ws-external --unsafe-rpc-external --ws-port 9945 --rpc-cors all --pruning archive --alice --node-key aa788920201122290fc7d3faf00698d9a8e061d7173424da2a31a8130a882a5f
        networks:
            testing_net:
                ipv4_address: 172.28.1.1

    node_bob:
        image: lsaether/polkadot:fast-fixed
        ports:
            - "30334:30334"
        volumes:
            - "polkadot-data-bob:/bob"
        links:
            - "node_alice:alice"
        command: polkadot --chain=polkadot-local --telemetry-url ws://172.28.1.3:8000/submit --validator --pruning archive --bob --bootnodes /ip4/172.28.1.1/tcp/30335/p2p/QmT5MYjkTDpoREKZTS7qHLSKPCJubTwYqfr6YQmhfcFYro --port 30334
        networks:
            testing_net:
                ipv4_address: 172.28.1.2

    telemetry:
        image: web3f/substrate-telemetry
        ports:
            - "8000:8000"
        networks:
            testing_net:
                ipv4_address: 172.28.1.3
    
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            testing_net:
                ipv4_address: 172.28.1.5

    1kv:
        build: .
        ports:
            - "3300:3300"
        networks:
            testing_net:
                ipv4_address: 172.28.1.4

volumes:
    polkadot-data-alice:
    polkadot-data-bob:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
