db_uri: "mongodb://localhost:27017/"
db_name: "candidate_verifier"
services:
  - telemetry_watcher:
      telemetry_host: "wss://telemetry-backend.w3f.community/feed"
      network: "polkadot"
      store_behavior:
        type: store
