rest_api:
  listen_addr: "localhost"
  port: 8080
  endpoints:
    health: true
    downtime: false
services:
  - validator_monitor:
      telemetry_host: "wss://telemetry-backend.w3f.community/feed"
      network: "polkadot"
      rpc_hosts:
        # Specify multiple (fallback) hosts in case one cannot be reached.
        # Prioritized by order.
        - "wss://rpc.polkadot.io"
        - "wss://cc1-1.polkadot.network"
      grace_period: 300
      store_behavior:
      candidate_file: "config/polkadot_candidates.yml"
