db_uri: "mongodb://localhost:27017/"
db_name: "candidate_verifier"
telemetry_watcher:
  enabled: true
  config:
    telemetry_host: "wss://telemetry-backend.w3f.community/feed"
    networks:
      - "polkadot"
      - "kusama"
candidate_verifier:
  enabled: false