environments:
  ci:
  local:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: otv-candidate-verifier-mongodb
  {{ if eq .Environment.Name "production" }}
  namespace: kusama
  {{ end }}
  chart: bitnami/mongodb
  version: 10.0.5
  values:
  - ./config/mongodb.yaml.gotmpl